In [1]:
import pandas as pd  # Importing pandas for data manipulation
from sklearn.model_selection import train_test_split  # Importing train_test_split from sklearn

In [2]:
# Let's start by loading our dataset into a pandas DataFrame.
car_data = pd.read_csv('fuel_efficiency_data.csv')  # Reading the CSV file into a DataFrame

In [3]:
# Separating the independent variable (Engine Size in Liters) and dependent variable (Fuel Efficiency in MPG).
indp_vars = car_data[['Engine_Size_Liters']]  # Selecting the 'Engine_Size_Liters' column as independent variable
dep_var = car_data['Fuel_Efficiency_MPG']  # Selecting the 'Fuel_Efficiency_MPG' column as dependent variable

In [4]:
# Splitting the data into training and testing sets.
train_x, test_x, train_y, test_y = train_test_split(indp_vars, dep_var, test_size=0.1, random_state=42)  # Splitting the data with 80% for training and 20% for testing
test_x

    Engine_Size_Liters
83            4.353535
53            3.141414
70            3.828283
45            2.818182
44            2.777778
39            2.575758
22            1.888889
80            4.232323
10            1.404040
0             1.000000

In [5]:
train_x, test_x, train_y, test_y = train_test_split(indp_vars, dep_var, test_size=0.1, random_state=101)  # Splitting the data with 80% for training and 20% for testing
test_x

    Engine_Size_Liters
16            1.646465
1             1.040404
43            2.737374
67            3.707071
89            4.595960
21            1.848485
97            4.919192
51            3.060606
6             1.242424
41            2.656566

In [6]:
train_x, test_x, train_y, test_y = train_test_split(indp_vars, dep_var, test_size=0.1)  # Splitting the data with 80% for training and 20% for testing
test_x

    Engine_Size_Liters
11            1.444444
39            2.575758
96            4.878788
8             1.323232
74            3.989899
87            4.515152
32            2.292929
76            4.070707
33            2.333333
14            1.565657